create database admin;
use admin;
create table students(Id int,Firstname varchar(20),Lastname varchar(20),Class int,Section varchar(20),Email varchar(50),Age int);
alter table students add primary key (Id);
insert into students values(127,'Venkata Padmini','B',10,'A','padmini@gmail.com',16);
insert into students values(161,'Naga Praneetha','N',9,'B','praneetha@gmail.com',15);
insert into students values(159,'Bhavitha','N',8,'C','bhavitha@gmail.com',14);
insert into students values(318,'Harsha','P',9,'B','harsha@gmail.com',15);
insert into students values(251,'Lavanya','D',8,'C','lavanya@gmail.com',14);
insert into students values(258,'Sameena','Sk',10,'A','sameena@gmail.com',16);
insert into students values(173,'Jayasree','N',8,'D','jayasree@gmail.com',14);
select * from students;
create table subjects(Id int,Name varchar(20),Shortcut varchar(20),Class int);
insert into subjects values(1,'Telugu','Tel',7);
insert into subjects values(2,'Hindi','Hin',6);
insert into subjects values(3,'English','Eng',2);
insert into subjects values(4,'Maths','Math',8);
insert into subjects values(5,'Science','Sci',10);
insert into subjects values(6,'Social','Soc',9);
insert into subjects values(7,'Computer','Com',4);
insert into subjects values(8,'General Knowledge','Gk',6);
insert into subjects values(9,'Sports','Sp',1);
select * from subjects;
create table teachers(Id int,Firstname varchar(20),Lastname varchar(20),Age int);
insert into teachers values(1,'Amar','J',35);
insert into teachers values(2,'Jyostna','B',40);
insert into teachers values(3,'Nirupam','P',35);
insert into teachers values(4,'Phani','S',35);
insert into teachers values(5,'Ram','P',35);
insert into teachers values(6,'John','K',40);
insert into teachers values(7,'Sam','C',35);
insert into teachers values(8,'prasad','J',35);
insert into teachers values(9,'Sita','A',27);
insert into teachers values(10,'Venkat','K',50);
select * from teachers;
create table classes(Id int,Section varchar(20),Teacher varchar(20),Subject varchar(20),Time varchar(20));
insert into classes values(9,'B','Jyostna','Maths','9:00');
insert into classes values(10,'A','Nirupam','Social','10:00');
insert into classes values(8,'A','Ram','Science','11:00');
insert into classes values(7,'C','Amar','English','12:00');
insert into classes values(6,'D','Phani','Telugu','1:00');
insert into classes values(5,'E','Sam','Hindi','2:00');
insert into classes values(4,'F','John','Computer','8:00');
insert into classes values(3,'B','Prasad','General Knowledge','3:00');
insert into classes values(2,'D','Jyostna','English','4:00');
insert into classes values(1,'A','Nirupam','English','9:00');
insert into classes values(9,'B','Nirupam','English','10:00');
select * from classes;
ALTER TABLE students ADD PRIMARY KEY (Id);
ALTER TABLE subjects  ADD PRIMARY KEY (Id);
ALTER TABLE teachers  ADD PRIMARY KEY (Id);
